/**
 * The built-in exercise catalogue.
 *
 * These are common, widely-prescribed home-program movements — the ones people
 * are most likely to be handed on a photocopied sheet. They are here so a user
 * can find their exercise instead of typing it, NOT as a program to follow.
 * Nothing in this file is a recommendation: what you do, how much, and how
 * often comes from your own therapist. Anything they gave you that isn't here
 * can be added as a custom exercise.
 *
 * `metric` is what the webcam can put a number on. Plenty of good exercises
 * have none — rotation, resisted work, and fine coordination don't survive a
 * flat 2D camera, and it's more honest to say so than to invent a number.
 */
import type { Exercise } from './types';

type Seed = Omit<Exercise, 'builtIn' | 'createdAt'>;

const seeds: Seed[] = [
  // ---------------------------------------------------------------- shoulder
  {
    id: 'shoulder-flexion-active',
    name: 'Shoulder flexion (arm raise forward)',
    category: 'shoulder-elbow',
    summary: 'Lift your arm straight out in front and up overhead, as far as is comfortable.',
    steps: [
      'Sit or stand tall with your arm hanging at your side, thumb facing forward.',
      'Raise the arm forward and up, keeping the elbow as straight as you can.',
      'Go to the point of a gentle stretch — not pain — and pause.',
      'Lower slowly, taking about twice as long as the lift.',
    ],
    cues: [
      'Do not shrug — let the shoulder blade slide, not hike up to your ear.',
      'Keep your ribs down; arching your back fakes extra range.',
    ],
    safety: 'Sharp or pinching pain at the top means stop and check with your therapist.',
    strokeNote:
      'Often done with the other hand supporting or clasping the affected one. Log which way you did it in the notes, because assisted and unassisted range are different numbers.',
    metric: 'shoulder-flexion',
    defaultTarget: 120,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    tags: ['shoulder', 'rom', 'stroke', 'frozen shoulder', 'rotator cuff'],
  },
  {
    id: 'shoulder-abduction-active',
    name: 'Shoulder abduction (arm raise to the side)',
    category: 'shoulder-elbow',
    summary: 'Lift your arm out sideways, away from your body.',
    steps: [
      'Stand or sit facing the camera with the arm at your side.',
      'Raise the arm out to the side, palm down, elbow straight.',
      'Stop at a comfortable end point and hold briefly.',
      'Lower under control.',
    ],
    cues: [
      'Turn the palm up as you pass shoulder height if it feels pinchy.',
      'Keep your trunk upright — leaning away is the most common cheat.',
    ],
    metric: 'shoulder-abduction',
    defaultTarget: 110,
    targetDirection: 'increase',
    cameraView: 'front',
    bilateral: true,
    tags: ['shoulder', 'rom', 'stroke'],
  },
  {
    id: 'pendulum-swings',
    name: 'Pendulum (Codman) swings',
    category: 'shoulder-elbow',
    summary: 'Let the arm hang and swing loosely — a gentle way to move a painful shoulder.',
    steps: [
      'Lean forward, supporting yourself on a table with your good arm.',
      'Let the other arm hang straight down, completely relaxed.',
      'Shift your weight to swing the arm in small circles, then front to back.',
      'Reverse the circle direction halfway through.',
    ],
    cues: [
      'The arm should be moved by your body, not by your shoulder muscles.',
      'Small circles. This is a relaxation exercise, not a stretch.',
    ],
    strokeNote: 'Frequently prescribed early on to protect a subluxed or painful shoulder.',
    bilateral: true,
    holdBased: false,
    tags: ['shoulder', 'pain', 'mobility'],
  },
  {
    id: 'table-slides',
    name: 'Table slides (assisted shoulder flexion)',
    category: 'shoulder-elbow',
    summary: 'Slide your forearm forward across a table so gravity does not fight you.',
    steps: [
      'Sit at a table with a towel or cloth under your forearm.',
      'Slide the arm forward, letting your trunk lean in as you reach.',
      'Reach as far as comfortable, hold, then slide back.',
    ],
    cues: [
      'The towel is doing the work of holding the arm up — stay relaxed.',
      'Mark how far you got on the table so you can chase it next time.',
    ],
    strokeNote:
      'A staple early upper-limb exercise: it lets you move through range with much less effort than lifting against gravity.',
    metric: 'shoulder-flexion',
    defaultTarget: 90,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    equipment: ['table', 'towel'],
    tags: ['shoulder', 'assisted', 'stroke', 'rom'],
  },
  {
    id: 'wall-walk',
    name: 'Wall walk (finger ladder)',
    category: 'shoulder-elbow',
    summary: 'Walk your fingers up a wall to coax the shoulder higher each time.',
    steps: [
      'Stand facing or side-on to a wall, fingertips on the wall at waist height.',
      'Walk the fingers upward, stepping closer to the wall as the arm rises.',
      'Stop at a gentle stretch, hold a few seconds, then walk back down.',
    ],
    cues: ['Let your fingers carry the arm — do not muscle it up.'],
    metric: 'shoulder-flexion',
    defaultTarget: 130,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    equipment: ['wall'],
    tags: ['shoulder', 'rom', 'frozen shoulder'],
  },
  {
    id: 'shoulder-external-rotation',
    name: 'Shoulder external rotation',
    category: 'shoulder-elbow',
    summary: 'With the elbow tucked at your side, rotate the forearm outward.',
    steps: [
      'Elbow bent to 90° and held against your ribs, forearm across your stomach.',
      'Keeping the elbow pinned, rotate the forearm outward, away from your body.',
      'Return slowly to the start.',
    ],
    cues: [
      'A rolled towel between elbow and ribs stops the elbow drifting.',
      'The movement is a small arc. It should not involve your shoulder lifting.',
    ],
    safety: 'Common after shoulder surgery — respect any range limit you were given.',
    bilateral: true,
    equipment: ['towel', 'resistance band (optional)'],
    tags: ['shoulder', 'rotator cuff', 'rotation'],
  },
  {
    id: 'scapular-retraction',
    name: 'Shoulder blade squeezes',
    category: 'shoulder-elbow',
    summary: 'Draw your shoulder blades together to wake up the muscles that hold your posture.',
    steps: [
      'Sit or stand tall, arms relaxed by your sides.',
      'Gently squeeze the shoulder blades back and down, as if pinching something between them.',
      'Hold, then release completely.',
    ],
    cues: ['Down as well as back — do not let the shoulders ride up.'],
    strokeNote: 'Helps counter the pulled-forward posture that develops on the affected side.',
    bilateral: false,
    holdBased: true,
    tags: ['posture', 'scapula', 'stroke'],
  },
  {
    id: 'shoulder-shrugs',
    name: 'Shoulder shrugs',
    category: 'shoulder-elbow',
    summary: 'Lift both shoulders toward your ears and let them drop.',
    steps: ['Sit tall.', 'Shrug both shoulders up.', 'Hold briefly.', 'Let them drop and relax.'],
    cues: ['The release matters as much as the lift.'],
    bilateral: false,
    tags: ['shoulder', 'neck', 'warm-up'],
  },
  {
    id: 'self-assisted-overhead-press',
    name: 'Clasped-hands overhead reach',
    category: 'shoulder-elbow',
    summary: 'Clasp your hands together and let the stronger arm help the weaker one reach up.',
    steps: [
      'Interlace your fingers, or hold the affected hand with the other one.',
      'Straighten the elbows and raise both arms forward and up together.',
      'Go to a gentle stretch, hold, then lower together.',
    ],
    cues: ['The strong arm guides; the affected arm should still try to help.'],
    strokeNote:
      'Classic self-range-of-motion exercise. Keeping the affected arm actively trying — not just along for the ride — is the point.',
    metric: 'shoulder-flexion',
    defaultTarget: 140,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: false,
    tags: ['shoulder', 'assisted', 'stroke', 'rom'],
  },
  {
    id: 'horizontal-abduction',
    name: 'Chest opener (horizontal abduction)',
    category: 'shoulder-elbow',
    summary: 'Open both arms wide to stretch across the front of the chest.',
    steps: [
      'Sit or stand with arms out in front at shoulder height.',
      'Open the arms wide to the sides, leading with your thumbs.',
      'Feel the stretch across the chest, hold, then bring them back together.',
    ],
    cues: ['Keep the neck long and the chin tucked.'],
    bilateral: false,
    tags: ['shoulder', 'chest', 'posture'],
  },

  // ------------------------------------------------------------------- elbow
  {
    id: 'elbow-flexion',
    name: 'Elbow bends (biceps curl)',
    category: 'shoulder-elbow',
    summary: 'Bend the elbow to bring your hand toward your shoulder.',
    steps: [
      'Sit side-on to the camera with the upper arm hanging at your side.',
      'Bend the elbow, bringing your hand up toward your shoulder.',
      'Hold at the top, then lower slowly and fully straighten.',
    ],
    cues: [
      'Keep the upper arm still — only the forearm moves.',
      'Straightening all the way at the bottom matters as much as the bend.',
    ],
    strokeNote:
      'The elbow often wants to stay bent after a stroke. Getting all the way to straight is usually the harder and more valuable half of this exercise.',
    metric: 'elbow-flexion',
    defaultTarget: 120,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    equipment: ['light weight (optional)'],
    tags: ['elbow', 'strength', 'rom', 'stroke'],
  },
  {
    id: 'elbow-extension',
    name: 'Elbow straightening',
    category: 'shoulder-elbow',
    summary: 'Work on getting the elbow fully straight.',
    steps: [
      'Rest the upper arm on a table or the arm of a chair, forearm hanging.',
      'Straighten the elbow as far as it will go.',
      'Hold at end range, then let it bend again.',
    ],
    cues: ['Slow and sustained beats forceful and quick.'],
    safety: 'Never push or bounce a stiff elbow into straightening. Steady pressure only.',
    strokeNote: 'Directly targets the flexed-elbow pattern that limits reaching.',
    metric: 'elbow-flexion',
    defaultTarget: 10,
    targetDirection: 'decrease',
    cameraView: 'side',
    bilateral: true,
    tags: ['elbow', 'rom', 'contracture', 'stroke'],
  },
  {
    id: 'forearm-rotation',
    name: 'Palm up, palm down (supination / pronation)',
    category: 'shoulder-elbow',
    summary: 'With the elbow bent at your side, turn the palm up and then down.',
    steps: [
      'Elbow bent to 90° and tucked against your side, forearm pointing forward.',
      'Turn the palm to face the ceiling, hold.',
      'Turn it to face the floor, hold.',
    ],
    cues: ['The elbow stays glued to your side — the rotation is in the forearm.'],
    strokeNote:
      'Turning the palm up is a very common sticking point and it matters for eating, washing, and taking pills.',
    bilateral: true,
    tags: ['forearm', 'rotation', 'stroke', 'adl'],
  },

  // -------------------------------------------------------------- hand/wrist
  {
    id: 'wrist-flexion-extension',
    name: 'Wrist up and down',
    category: 'hand-wrist',
    summary: 'Bend the wrist back and forward with the forearm supported.',
    steps: [
      'Rest the forearm on a table with the hand hanging off the edge.',
      'Lift the hand upward as far as comfortable, hold.',
      'Lower it downward as far as comfortable, hold.',
    ],
    cues: ['The forearm must stay flat on the table; only the wrist moves.'],
    metric: 'wrist-deviation',
    defaultTarget: 45,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    equipment: ['table'],
    tags: ['wrist', 'rom', 'stroke'],
  },
  {
    id: 'wrist-deviation',
    name: 'Wrist side to side',
    category: 'hand-wrist',
    summary: 'Move the hand toward the thumb side, then the little-finger side.',
    steps: [
      'Rest the forearm flat, palm down, hand off the edge of the table.',
      'Move the hand toward the thumb side, then toward the little-finger side.',
    ],
    cues: ['Keep the forearm still and the wrist flat — no lifting.'],
    bilateral: true,
    equipment: ['table'],
    tags: ['wrist', 'rom'],
  },
  {
    id: 'make-a-fist',
    name: 'Making a fist',
    category: 'hand-wrist',
    summary: 'Close the fingers into a fist and open them fully.',
    steps: [
      'Hold your hand up in front of the camera, fingers straight.',
      'Curl the fingers slowly into a fist, thumb outside.',
      'Hold, then open the hand as wide as it will go.',
    ],
    cues: ['Full open matters as much as full closed.', 'Move slowly — speed hides stiffness.'],
    strokeNote:
      'Opening the hand is usually much harder than closing it. Give the opening half the extra time.',
    metric: 'hand-close',
    defaultTarget: 80,
    targetDirection: 'increase',
    cameraView: 'either',
    bilateral: true,
    tags: ['hand', 'fingers', 'grasp', 'stroke'],
  },
  {
    id: 'finger-extension',
    name: 'Opening the hand (finger extension)',
    category: 'hand-wrist',
    summary: 'Straighten every finger out flat from a relaxed curl.',
    steps: [
      'Start with the hand relaxed and lightly curled.',
      'Straighten the fingers and thumb out as flat as you can.',
      'Hold at the fullest point, then relax.',
    ],
    cues: ['Try to lead with the knuckles, not just the fingertips.'],
    strokeNote:
      'The single most commonly lost hand movement after a stroke, and the one that unlocks letting go of objects.',
    metric: 'hand-open',
    defaultTarget: 80,
    targetDirection: 'increase',
    cameraView: 'either',
    bilateral: true,
    tags: ['hand', 'fingers', 'release', 'stroke'],
  },
  {
    id: 'tabletop-intrinsic-plus',
    name: 'Tabletop (knuckle bends)',
    category: 'hand-wrist',
    summary: 'Bend at the big knuckles while keeping the fingers themselves straight.',
    steps: [
      'Hold the hand up, fingers straight and together.',
      'Bend only at the knuckles so the fingers form a flat shelf.',
      'Hold, then straighten back out.',
    ],
    cues: ['The finger joints past the knuckle stay straight — this is the hard part.'],
    metric: 'index-mcp-flexion',
    defaultTarget: 70,
    targetDirection: 'increase',
    cameraView: 'either',
    bilateral: true,
    tags: ['hand', 'fingers', 'dexterity'],
  },
  {
    id: 'thumb-opposition',
    name: 'Thumb to fingertips',
    category: 'hand-wrist',
    summary: 'Touch your thumb to each fingertip in turn, then sweep it across the palm.',
    steps: [
      'Touch thumb to index tip, then middle, ring, and little finger.',
      'Then reach the thumb across the palm toward the base of the little finger.',
      'Open the hand fully between repetitions.',
    ],
    cues: ['Aim for tip to tip, making a round O shape each time.'],
    metric: 'thumb-opposition',
    defaultTarget: 75,
    targetDirection: 'increase',
    cameraView: 'either',
    bilateral: true,
    tags: ['thumb', 'dexterity', 'adl', 'stroke'],
  },
  {
    id: 'finger-spread',
    name: 'Finger spreads',
    category: 'hand-wrist',
    summary: 'Spread the fingers wide apart, then bring them back together.',
    steps: [
      'Rest the hand flat, palm down, or hold it up to the camera.',
      'Spread the fingers as wide apart as they will go.',
      'Hold, then draw them back together.',
    ],
    cues: ['Keep the fingers straight while spreading.'],
    metric: 'finger-spread',
    defaultTarget: 40,
    targetDirection: 'increase',
    cameraView: 'either',
    bilateral: true,
    tags: ['hand', 'fingers', 'dexterity'],
  },
  {
    id: 'tip-pinch',
    name: 'Tip pinch',
    category: 'hand-wrist',
    summary: 'Pinch thumb and index finger together, as if picking up a coin.',
    steps: [
      'Hold the hand up with thumb and index finger apart.',
      'Bring the tips together and squeeze gently.',
      'Hold, then open the pinch wide again.',
    ],
    cues: ['Both the squeeze and the wide opening count.'],
    metric: 'pinch-aperture',
    defaultTarget: 15,
    targetDirection: 'decrease',
    cameraView: 'either',
    bilateral: true,
    tags: ['pinch', 'dexterity', 'adl'],
  },
  {
    id: 'grip-squeeze',
    name: 'Grip squeezes (ball or putty)',
    category: 'hand-wrist',
    summary: 'Squeeze a soft ball or piece of therapy putty and fully release.',
    steps: [
      'Hold a soft ball or putty in the palm.',
      'Squeeze steadily for a few seconds.',
      'Release completely and let the hand open.',
    ],
    cues: ['The release is the rehab. Do not go straight into the next squeeze.'],
    safety: 'Stop if you get numbness or tingling into the fingers.',
    bilateral: true,
    holdBased: true,
    equipment: ['soft ball', 'therapy putty'],
    tags: ['grip', 'strength', 'hand'],
  },

  // ---------------------------------------------------------------- hip/knee
  {
    id: 'sit-to-stand',
    name: 'Sit to stand',
    category: 'functional',
    summary: 'Stand up from a chair and sit back down under control — the single most useful thing you can practise.',
    steps: [
      'Sit toward the front of a sturdy chair, feet flat and slightly back.',
      'Lean your nose over your toes.',
      'Push up through both feet to stand tall.',
      'Sit back down slowly, reaching your hips back for the chair.',
    ],
    cues: [
      'Weight through both feet, including the weaker one.',
      'Lowering slowly builds more strength than standing up does.',
    ],
    safety:
      'Use a chair with arms and against a wall until you are confident. Have someone nearby the first few times.',
    strokeNote:
      'The best single measure of lower-limb function, and it carries straight over into daily life.',
    metric: 'knee-flexion',
    defaultTarget: 85,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: false,
    equipment: ['sturdy chair'],
    tags: ['functional', 'strength', 'balance', 'stroke', 'adl'],
  },
  {
    id: 'heel-slides',
    name: 'Heel slides',
    category: 'hip-knee',
    summary: 'Lying or sitting, slide the heel toward you to bend the knee.',
    steps: [
      'Lie on your back with legs straight, or sit with the leg out in front.',
      'Slide the heel toward your bottom, bending the knee.',
      'Hold at the end of the bend, then slide back out to straight.',
    ],
    cues: ['A plastic bag or towel under the heel makes it slide.'],
    metric: 'knee-flexion',
    defaultTarget: 90,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    equipment: ['towel'],
    tags: ['knee', 'rom', 'post-op', 'acl'],
  },
  {
    id: 'long-arc-quad',
    name: 'Seated knee straightening (long arc quad)',
    category: 'hip-knee',
    summary: 'From sitting, straighten the knee out in front of you.',
    steps: [
      'Sit tall in a chair, both feet on the floor.',
      'Straighten one knee until the leg is out in front.',
      'Hold, tighten the thigh, then lower slowly.',
    ],
    cues: ['Squeeze the thigh hard at the top — that squeeze is the exercise.'],
    metric: 'knee-flexion',
    defaultTarget: 5,
    targetDirection: 'decrease',
    cameraView: 'side',
    bilateral: true,
    equipment: ['chair'],
    tags: ['knee', 'quadriceps', 'strength', 'post-op'],
  },
  {
    id: 'straight-leg-raise',
    name: 'Straight leg raise',
    category: 'hip-knee',
    summary: 'Lift the whole leg with the knee locked straight.',
    steps: [
      'Lie on your back, one knee bent with the foot flat, the other leg straight.',
      'Tighten the thigh of the straight leg and lift it to the height of the opposite knee.',
      'Hold, then lower slowly.',
    ],
    cues: ['The knee must not bend at all. If it does, lower the target height.'],
    safety: 'Stop if you get low back pain — press your back into the floor first.',
    metric: 'hip-flexion',
    defaultTarget: 45,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    tags: ['hip', 'quadriceps', 'strength', 'post-op'],
  },
  {
    id: 'seated-marching',
    name: 'Seated marching',
    category: 'hip-knee',
    summary: 'Lift each knee in turn while sitting, like marching in a chair.',
    steps: [
      'Sit tall, both feet flat on the floor.',
      'Lift one knee up toward the ceiling.',
      'Lower it with control and repeat on the other side.',
    ],
    cues: ['Sit tall — do not lean back to make the lift easier.'],
    metric: 'hip-flexion',
    defaultTarget: 60,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    equipment: ['chair'],
    tags: ['hip', 'strength', 'seated', 'stroke'],
  },
  {
    id: 'standing-marching',
    name: 'Standing marching',
    category: 'hip-knee',
    summary: 'March on the spot, lifting each knee, holding on for support.',
    steps: [
      'Stand holding a counter or sturdy chair back.',
      'Lift one knee toward hip height.',
      'Lower with control, then lift the other.',
    ],
    cues: ['Stay tall. Do not let the hip hike up to do the lifting.'],
    safety: 'Always have support within reach.',
    metric: 'hip-flexion',
    defaultTarget: 70,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    equipment: ['counter or chair for support'],
    tags: ['hip', 'balance', 'gait', 'stroke'],
  },
  {
    id: 'standing-hip-abduction',
    name: 'Standing leg lift to the side',
    category: 'hip-knee',
    summary: 'Lift the leg out sideways while standing tall.',
    steps: [
      'Stand facing the camera, holding a support.',
      'Lift one leg out to the side, keeping the knee straight and toes forward.',
      'Hold briefly, then lower.',
    ],
    cues: ['Do not lean away from the lifting leg — that is the whole trick.'],
    metric: 'hip-abduction',
    defaultTarget: 30,
    targetDirection: 'increase',
    cameraView: 'front',
    bilateral: true,
    equipment: ['counter or chair for support'],
    tags: ['hip', 'glutes', 'balance', 'gait'],
  },
  {
    id: 'standing-hamstring-curl',
    name: 'Standing heel curls',
    category: 'hip-knee',
    summary: 'Bend the knee to bring the heel toward your bottom while standing.',
    steps: [
      'Stand tall, holding a support.',
      'Bend one knee, bringing the heel up behind you.',
      'Hold, then lower slowly.',
    ],
    cues: ['Keep the thighs level with each other; the hip should not swing back.'],
    metric: 'knee-flexion',
    defaultTarget: 90,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    equipment: ['counter or chair for support'],
    tags: ['knee', 'hamstring', 'strength'],
  },
  {
    id: 'bridging',
    name: 'Bridging',
    category: 'hip-knee',
    summary: 'Lying on your back, lift your hips off the floor.',
    steps: [
      'Lie on your back, knees bent, feet flat and hip-width apart.',
      'Squeeze your bottom and lift your hips toward the ceiling.',
      'Hold, then lower slowly one vertebra at a time.',
    ],
    cues: ['Push evenly through both heels — it is easy to let the strong side take over.'],
    strokeNote: 'Builds the hip control needed for rolling in bed and for standing up.',
    bilateral: false,
    holdBased: true,
    tags: ['hip', 'glutes', 'core', 'stroke'],
  },
  {
    id: 'mini-squat',
    name: 'Mini squats',
    category: 'hip-knee',
    summary: 'Small, controlled knee bends while standing.',
    steps: [
      'Stand holding a counter, feet hip-width apart.',
      'Bend the knees a small way, keeping the heels down.',
      'Push back up to standing.',
    ],
    cues: ['Knees track over the middle toes, not inward.'],
    safety: 'Small range first. Depth comes later.',
    metric: 'knee-flexion',
    defaultTarget: 45,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: false,
    equipment: ['counter for support'],
    tags: ['knee', 'strength', 'functional'],
  },
  {
    id: 'step-ups',
    name: 'Step ups',
    category: 'hip-knee',
    summary: 'Step up onto a low step and back down, leading with one leg.',
    steps: [
      'Stand in front of a low step, holding a rail.',
      'Step up with the leading leg, then bring the other foot up.',
      'Step back down leading with the opposite leg.',
    ],
    cues: ['Push through the whole foot of the leading leg, not the toes.'],
    safety: 'Use a rail. Start with the lowest step you have.',
    metric: 'knee-flexion',
    defaultTarget: 70,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    equipment: ['step', 'handrail'],
    tags: ['functional', 'strength', 'gait', 'stairs'],
  },

  // -------------------------------------------------------------- ankle/foot
  {
    id: 'ankle-pumps',
    name: 'Ankle pumps',
    category: 'ankle-foot',
    summary: 'Point and flex the foot up and down.',
    steps: [
      'Sit or lie with the leg supported and straight.',
      'Pull the toes up toward your shin.',
      'Then point them away, like pressing a pedal.',
    ],
    cues: ['Move through the biggest range you can, slowly.'],
    metric: 'ankle-dorsiflexion',
    defaultTarget: 10,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    tags: ['ankle', 'circulation', 'rom', 'post-op'],
  },
  {
    id: 'heel-raises',
    name: 'Heel raises',
    category: 'ankle-foot',
    summary: 'Rise onto your toes and lower back down.',
    steps: [
      'Stand holding a counter, feet hip-width apart.',
      'Rise up onto the balls of your feet.',
      'Hold at the top, then lower slowly.',
    ],
    cues: ['Lower slowly — three seconds down.'],
    bilateral: true,
    equipment: ['counter for support'],
    tags: ['ankle', 'calf', 'strength', 'balance'],
  },
  {
    id: 'ankle-alphabet',
    name: 'Ankle alphabet',
    category: 'ankle-foot',
    summary: 'Trace the letters of the alphabet in the air with your big toe.',
    steps: [
      'Sit with the foot off the floor.',
      'Draw each letter A to Z in the air using only the ankle.',
    ],
    cues: ['Big letters. The leg stays still; only the ankle draws.'],
    bilateral: true,
    tags: ['ankle', 'rom', 'coordination'],
  },
  {
    id: 'calf-stretch',
    name: 'Calf stretch at the wall',
    category: 'ankle-foot',
    summary: 'A held stretch for a tight calf and Achilles.',
    steps: [
      'Stand facing a wall, hands on it, one foot back.',
      'Keep the back knee straight and the heel down.',
      'Lean in until you feel a stretch in the back calf, and hold.',
    ],
    cues: ['The back foot points straight at the wall, not turned out.'],
    strokeNote: 'A tight calf is one of the main reasons the foot catches when walking.',
    bilateral: true,
    holdBased: true,
    equipment: ['wall'],
    tags: ['calf', 'stretch', 'gait', 'stroke'],
  },

  // -------------------------------------------------------------- trunk/neck
  {
    id: 'seated-trunk-rotation',
    name: 'Seated trunk rotation',
    category: 'trunk-neck',
    summary: 'Turn your upper body to look over each shoulder.',
    steps: [
      'Sit tall with feet flat, arms crossed over your chest.',
      'Turn your upper body to one side, hold.',
      'Return to centre and turn the other way.',
    ],
    cues: ['Turn from the ribs, not just the neck. Hips stay facing forward.'],
    bilateral: false,
    tags: ['trunk', 'rotation', 'mobility'],
  },
  {
    id: 'seated-side-bend',
    name: 'Seated side bend',
    category: 'trunk-neck',
    summary: 'Lean your upper body to one side and come back to upright.',
    steps: [
      'Sit tall facing the camera.',
      'Slide one hand down the outside of your leg, bending sideways.',
      'Return to upright, then repeat to the other side.',
    ],
    cues: ['Bend sideways, not forward. Both sit bones stay down.'],
    strokeNote:
      'Regaining trunk control on the affected side underpins sitting balance and reaching.',
    metric: 'trunk-lateral-flexion',
    defaultTarget: 25,
    targetDirection: 'increase',
    cameraView: 'front',
    bilateral: true,
    tags: ['trunk', 'balance', 'stroke'],
  },
  {
    id: 'seated-forward-reach',
    name: 'Seated forward reach',
    category: 'trunk-neck',
    summary: 'Reach forward past your knees and return, without losing your balance.',
    steps: [
      'Sit tall with feet flat.',
      'Reach both hands forward and down past your knees.',
      'Come back up to tall sitting under control.',
    ],
    cues: ['Keep your feet down. Come back up without pushing off your thighs.'],
    safety: 'Do this with someone nearby if your sitting balance is not yet reliable.',
    metric: 'trunk-forward-flexion',
    defaultTarget: 40,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: false,
    tags: ['trunk', 'balance', 'stroke', 'reaching'],
  },
  {
    id: 'neck-rotation',
    name: 'Neck turns',
    category: 'trunk-neck',
    summary: 'Turn your head to look over each shoulder.',
    steps: ['Sit tall.', 'Turn your head slowly to one side, hold.', 'Return, then the other side.'],
    cues: ['Move only as far as comfortable. Never force the neck.'],
    safety:
      'Stop immediately if you get dizziness, visual changes, or nausea, and tell your doctor.',
    bilateral: false,
    tags: ['neck', 'rom'],
  },
  {
    id: 'chin-tucks',
    name: 'Chin tucks',
    category: 'trunk-neck',
    summary: 'Draw your chin straight back to lengthen the back of your neck.',
    steps: [
      'Sit or stand tall, eyes level.',
      'Draw the chin straight back, making a double chin.',
      'Hold, then release.',
    ],
    cues: ['Straight back, not down. Eyes stay level the whole time.'],
    bilateral: false,
    holdBased: true,
    tags: ['neck', 'posture'],
  },

  // ----------------------------------------------------------------- balance
  {
    id: 'standing-weight-shifts',
    name: 'Standing weight shifts',
    category: 'balance',
    summary: 'Shift your weight from one foot to the other while standing.',
    steps: [
      'Stand at a counter, feet hip-width apart.',
      'Slowly shift your weight onto one foot, then the other.',
      'Go a little further each time, staying in control.',
    ],
    cues: ['Move your hips sideways, not just lean your shoulders.'],
    safety: 'Counter in front of you at all times.',
    strokeNote:
      'Learning to trust weight on the affected leg is the foundation of walking again.',
    bilateral: false,
    equipment: ['counter for support'],
    tags: ['balance', 'gait', 'stroke'],
  },
  {
    id: 'single-leg-stance',
    name: 'Standing on one leg',
    category: 'balance',
    summary: 'Hold your balance on one leg for as long as you safely can.',
    steps: [
      'Stand at a counter with fingertips resting on it.',
      'Lift one foot slightly off the floor.',
      'Hold, then put it down and rest before the next go.',
    ],
    cues: ['Use fewer fingers on the counter as it gets easier, rather than letting go entirely.'],
    safety:
      'Always within arm’s reach of solid support. Do not attempt alone if you have fallen recently.',
    bilateral: true,
    holdBased: true,
    equipment: ['counter for support'],
    tags: ['balance', 'gait', 'falls'],
  },
  {
    id: 'tandem-stance',
    name: 'Heel-to-toe standing',
    category: 'balance',
    summary: 'Stand with one foot directly in front of the other and hold.',
    steps: [
      'Stand at a counter.',
      'Place one foot directly in front of the other, heel to toe.',
      'Hold steady, then switch which foot is in front.',
    ],
    cues: ['Look straight ahead at a fixed point, not at your feet.'],
    safety: 'Support within reach at all times.',
    bilateral: true,
    holdBased: true,
    equipment: ['counter for support'],
    tags: ['balance', 'falls'],
  },
  {
    id: 'heel-toe-walking',
    name: 'Heel-to-toe walking',
    category: 'balance',
    summary: 'Walk in a straight line placing each heel right in front of the other toe.',
    steps: [
      'Stand beside a counter or wall you can touch.',
      'Walk forward placing the heel of each step against the toes of the other foot.',
      'Take a set number of steps, turn around carefully, and come back.',
    ],
    cues: ['Slow. Eyes forward, not down.'],
    safety: 'Along a wall or counter. Never in open space until this feels easy.',
    bilateral: false,
    equipment: ['wall or counter'],
    tags: ['balance', 'gait', 'falls'],
  },

  // -------------------------------------------------------------- functional
  {
    id: 'hand-to-mouth',
    name: 'Hand to mouth',
    category: 'functional',
    summary: 'Practise bringing a cup or your hand to your mouth.',
    steps: [
      'Sit at a table with the elbow resting on it.',
      'Bring your hand up to your mouth.',
      'Lower it back to the table under control.',
    ],
    cues: ['Keep your head still and let the arm do the travelling.'],
    strokeNote: 'Directly rehearses eating and drinking, and it is a natural motivator.',
    metric: 'elbow-flexion',
    defaultTarget: 120,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    equipment: ['table', 'cup (optional)'],
    tags: ['adl', 'functional', 'stroke', 'elbow'],
  },
  {
    id: 'overhead-reach-shelf',
    name: 'Reaching to a shelf',
    category: 'functional',
    summary: 'Reach up as if putting something on a shelf.',
    steps: [
      'Stand side-on to the camera in front of a shelf or marked spot on the wall.',
      'Reach up and touch the target.',
      'Lower the arm under control.',
    ],
    cues: ['Do not go up on your toes to make the reach.'],
    metric: 'shoulder-flexion',
    defaultTarget: 140,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: true,
    tags: ['adl', 'functional', 'shoulder'],
  },
  {
    id: 'object-transfer',
    name: 'Moving objects across a table',
    category: 'functional',
    summary: 'Pick up small objects and move them from one side to the other.',
    steps: [
      'Set out several small objects — blocks, coins, clothes pegs.',
      'Pick each one up and place it in a container on the other side.',
      'Work as accurately as you can, then as quickly as you can.',
    ],
    cues: ['Accuracy first, then speed. Count how long a full set takes and log it.'],
    strokeNote:
      'A practical stand-in for the block-and-box tests used in clinic. Timing yourself gives you a real trend.',
    bilateral: true,
    equipment: ['small objects', 'two containers'],
    tags: ['adl', 'dexterity', 'stroke', 'timed'],
  },
  {
    id: 'sit-to-stand-no-hands',
    name: 'Sit to stand without hands',
    category: 'functional',
    summary: 'Standing up from a chair with your arms folded — a harder progression.',
    steps: [
      'Sit toward the front of a sturdy chair, arms folded across your chest.',
      'Lean forward and push up through both feet.',
      'Sit back down slowly without using your hands.',
    ],
    cues: ['If you cannot manage it, raise the seat height with a cushion rather than giving up.'],
    safety:
      'Only progress to this once sit-to-stand with hands is easy and steady. Have someone nearby.',
    metric: 'knee-flexion',
    defaultTarget: 85,
    targetDirection: 'increase',
    cameraView: 'side',
    bilateral: false,
    equipment: ['sturdy chair'],
    tags: ['functional', 'strength', 'progression'],
  },
];

export const BUILT_IN_EXERCISES: Exercise[] = seeds.map((s) => ({
  ...s,
  builtIn: true,
  createdAt: 0,
}));

export const BUILT_IN_BY_ID = new Map(BUILT_IN_EXERCISES.map((e) => [e.id, e]));
